### ISSUE TITLE
Fatal JS runtime error

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/naive-ui-todo#42]
```
Uncaught TypeError: Object(...) is not a function
```

`git bisect` points to (bc445f37e2583b8ed80d0a5d3aeafb0327124130).
